[phases.setup]
nixPkgs = ["python39", "git", "curl"]

[phases.install]
cmds = ["curl -L -o backend/best_mushroom_cnn.keras https://github.com/CalvinJ45/MushroomVision/raw/main/backend/best_mushroom_cnn.keras", "cd backend && pip install -r requirements.txt"]

[start]
cmd = "cd backend && python app.py"

