[phases.setup]
nixPkgs = ["python39", "git", "curl"]

[phases.install]
cmds = ["python download_model.py", "cd backend && pip install -r requirements.txt"]

[start]
cmd = "cd backend && python app.py"

